import json

# Leer notebook
ruta = r'C:\Users\Patricio\Documents\Codigo\Python\Investigacion\Tesis\Código\62.1. Cleveland CO - Comparaciones Entre Poblaciones.ipynb'
with open(ruta, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Encontrar celda nueva-6 y reemplazarla completamente
for i, cell in enumerate(nb['cells']):
    if cell.get('id') == 'nueva-6':
        # Reemplazar con código bien formateado
        nb['cells'][i]['source'] = [
            "def Crear_Cleveland_Con_Comparaciones(\n",
            "    df,\n",
            "    titulo,\n",
            "    comparaciones_sig=None,\n",
            "    nombre_archivo=None,\n",
            "    carpeta_destino='Graficos_Cleveland'\n",
            "):\n",
            "    if not os.path.exists(carpeta_destino):\n",
            "        os.makedirs(carpeta_destino)\n",
            "    \n",
            "    df_sorted = df.sort_values('Diferencia', ascending=True).reset_index(drop=True)\n",
            "    ancho = 16 if comparaciones_sig else 12\n",
            "    fig, ax = plt.subplots(figsize=(ancho, 10))\n",
            "    y_positions = np.arange(len(df_sorted))\n",
            "    \n",
            "    for idx, row in df_sorted.iterrows():\n",
            "        cong_val = row['CO_Congruente']\n",
            "        incong_val = row['CO_Incongruente']\n",
            "        diferencia = row['Diferencia']\n",
            "        if diferencia > 0.1:\n",
            "            color_linea = '#2ecc71'\n",
            "            alpha = 0.7\n",
            "        elif diferencia < -0.1:\n",
            "            color_linea = '#e74c3c'\n",
            "            alpha = 0.7\n",
            "        else:\n",
            "            color_linea = '#95a5a6'\n",
            "            alpha = 0.4\n",
            "        ax.plot([cong_val, incong_val], [idx, idx], color=color_linea, linewidth=2, alpha=alpha, zorder=1)\n",
            "    \n",
            "    ax.scatter(df_sorted['CO_Congruente'], y_positions, s=150, c='#3498db', marker='o',\n",
            "               edgecolors='white', linewidths=2, label='Congruente', zorder=3, alpha=0.9)\n",
            "    ax.scatter(df_sorted['CO_Incongruente'], y_positions, s=150, c='#e74c3c', marker='o',\n",
            "               edgecolors='white', linewidths=2, label='Incongruente', zorder=3, alpha=0.9)\n",
            "    ax.axvline(x=0, color='black', linestyle='--', linewidth=0.8, alpha=0.3, zorder=0)\n",
            "    \n",
            "    ax.set_yticks(y_positions)\n",
            "    etiquetas_con_sig = [f\"{row['Etiqueta']} {row['Significancia']}\" if row['Significancia'] else row['Etiqueta']\n",
            "                         for _, row in df_sorted.iterrows()]\n",
            "    ax.set_yticklabels(etiquetas_con_sig, fontsize=11)\n",
            "    ax.set_xlabel('Cambio de Opinión (promedio)', fontsize=12, fontweight='bold')\n",
            "    ax.set_ylabel('Categoría Ideológica', fontsize=12, fontweight='bold')\n",
            "    ax.set_title(titulo, fontsize=14, fontweight='bold', pad=20)\n",
            "    ax.grid(True, axis='x', alpha=0.3, linestyle=':', linewidth=0.5)\n",
            "    ax.set_axisbelow(True)\n",
            "    \n",
            "    # Dibujar corchetes\n",
            "    if comparaciones_sig and len(comparaciones_sig) > 0:\n",
            "        xlims = ax.get_xlim()\n",
            "        rango_x = xlims[1] - xlims[0]\n",
            "        x_bracket_base = xlims[1] + rango_x * 0.08\n",
            "        etiqueta_a_pos = {row['Etiqueta']: idx for idx, row in df_sorted.iterrows()}\n",
            "        \n",
            "        for i, (cat1, cat2, p_val, sig) in enumerate(comparaciones_sig[:5]):\n",
            "            if cat1 in etiqueta_a_pos and cat2 in etiqueta_a_pos:\n",
            "                y1, y2 = etiqueta_a_pos[cat1], etiqueta_a_pos[cat2]\n",
            "                y_min, y_max = min(y1, y2), max(y1, y2)\n",
            "                x_pos = x_bracket_base + i * rango_x * 0.05\n",
            "                color = '#e74c3c' if sig == '***' else '#e67e22' if sig == '**' else '#f39c12'\n",
            "                ax.plot([x_pos, x_pos], [y_min, y_max], color=color, linewidth=2, clip_on=False, zorder=10)\n",
            "                tick_len = rango_x * 0.015\n",
            "                ax.plot([x_pos, x_pos + tick_len], [y_max, y_max], color=color, linewidth=2, clip_on=False, zorder=10)\n",
            "                ax.plot([x_pos, x_pos + tick_len], [y_min, y_min], color=color, linewidth=2, clip_on=False, zorder=10)\n",
            "                ax.text(x_pos + tick_len * 1.5, (y_min + y_max) / 2, sig, fontsize=10, va='center',\n",
            "                       color=color, fontweight='bold', clip_on=False)\n",
            "    \n",
            "    # Leyenda FUERA del gráfico\n",
            "    legend_elements = [\n",
            "        Line2D([0], [0], marker='o', color='w', markerfacecolor='#3498db', markersize=11,\n",
            "               label='Congruente', markeredgecolor='white', markeredgewidth=1.5),\n",
            "        Line2D([0], [0], marker='o', color='w', markerfacecolor='#e74c3c', markersize=11,\n",
            "               label='Incongruente', markeredgecolor='white', markeredgewidth=1.5),\n",
            "        Line2D([0], [0], color='#2ecc71', linewidth=2.5, label='Mayor Incong (>0.1)'),\n",
            "        Line2D([0], [0], color='#95a5a6', linewidth=2.5, label='Similar (+-0.1)'),\n",
            "        Line2D([0], [0], color='#e74c3c', linewidth=2.5, label='Mayor Cong (<-0.1)'),\n",
            "        Line2D([0], [0], marker='', color='w', label='* Izq: Cong vs Incong'),\n",
            "        Line2D([0], [0], marker='', color='w', label='* Der: entre poblaciones')\n",
            "    ]\n",
            "    ax.legend(handles=legend_elements, loc='center left', bbox_to_anchor=(1.02, 0.5),\n",
            "              fontsize=9, framealpha=0.95, edgecolor='gray')\n",
            "    \n",
            "    plt.tight_layout()\n",
            "    if nombre_archivo:\n",
            "        ruta_completa = os.path.join(carpeta_destino, f'{nombre_archivo}.svg')\n",
            "        plt.savefig(ruta_completa, format='svg', bbox_inches='tight', facecolor='white')\n",
            "        print(f'Grafico guardado: {ruta_completa}')\n",
            "    plt.show()\n",
            "    return fig, ax\n",
            "\n",
            "# Generar graficos\n",
            "print('='*70)\n",
            "print('GRAFICOS CLEVELAND CON COMPARACIONES ENTRE POBLACIONES')\n",
            "print('='*70)\n",
            "\n",
            "for nombre_ds in ['Generales', 'Ballotage']:\n",
            "    print(f'\\n{nombre_ds}:')\n",
            "    print('-'*70)\n",
            "    _, comp_sig = Resultados_Comparaciones[nombre_ds].get('CO_Congruente', (None, []))\n",
            "    \n",
            "    if len(comp_sig) > 0:\n",
            "        print(f'  {len(comp_sig)} comparaciones significativas detectadas')\n",
            "        for cat1, cat2, p, sig in comp_sig[:5]:\n",
            "            print(f'    {sig} {cat1} vs {cat2} (p={p:.4f})')\n",
            "    else:\n",
            "        print(f'  No hay comparaciones significativas entre poblaciones')\n",
            "    \n",
            "    print(f'\\n  Generando grafico...')\n",
            "    fig, ax = Crear_Cleveland_Con_Comparaciones(\n",
            "        datos_graficos[nombre_ds],\n",
            "        titulo=f'CO Congruente vs Incongruente - {nombre_ds}\\n(con comparaciones entre poblaciones)',\n",
            "        comparaciones_sig=comp_sig,\n",
            "        nombre_archivo=f'Cleveland_CO_ConComparaciones_{nombre_ds}'\n",
            "    )\n",
            "\n",
            "print('\\n' + '='*70)\n",
            "print('GRAFICOS COMPLETADOS')\n",
            "print('='*70)"
        ]
        print(f'Celda nueva-6 encontrada en posicion {i} y reemplazada')
        break

# Guardar
with open(ruta, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print('OK - Celda nueva-6 corregida con leyenda fuera del grafico')
